import type { Metadata } from "next";
import { LegalLayout, H2, P, UL, A, LEGAL_CONTACT, LEGAL_OPERATOR } from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Character Studio",
  description:
    "The terms that govern use of Character Studio, including acceptable use, the Instagram/Meta integration rules, disclaimers, limitation of liability and termination.",
  robots: { index: true, follow: true },
};

const UPDATED = "24 July 2026";

export default function TermsOfServicePage() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated={UPDATED}
      intro={`These Terms of Service ("Terms") govern your use of Character Studio (the "Service"), operated by ${LEGAL_OPERATOR}. By accessing or using the Service you agree to these Terms. If you do not agree, do not use the Service.`}
    >
      <H2>1. The Service</H2>
      <P>
        Character Studio is a tool for creating AI-assisted content and for automatically classifying
        and replying to direct messages and comments on connected Instagram professional accounts. The
        Service uses AI models to draft responses and the Instagram Platform to receive and send them.
      </P>

      <H2>2. Eligibility</H2>
      <P>
        You must be at least 18 years old and able to enter into a binding agreement to use the Service.
        You may use the Service only for accounts you own or are authorised to manage.
      </P>

      <H2>3. Acceptable use</H2>
      <P>You agree not to use the Service to:</P>
      <UL>
        <li>break any applicable law or regulation;</li>
        <li>send spam, harassment, hateful, deceptive, or otherwise abusive content;</li>
        <li>impersonate others or misrepresent your identity or affiliation;</li>
        <li>send sexually explicit, threatening, or illegal content;</li>
        <li>
          scrape, reverse engineer, disrupt, or attempt to gain unauthorised access to the Service or
          its infrastructure;
        </li>
        <li>circumvent rate limits, security controls, or messaging restrictions.</li>
      </UL>

      <H2>4. Instagram and Meta integration</H2>
      <UL>
        <li>
          You must own, or be authorised to manage, any Instagram or Meta account you connect to the
          Service.
        </li>
        <li>
          Your use of the integration must comply with the Meta Platform Terms, the Instagram Platform
          Policy, the Instagram Community Guidelines, and Meta&rsquo;s Developer Policies.
        </li>
        <li>
          Meta is not a party to these Terms and does not sponsor or endorse the Service. Access is
          provided by Meta&rsquo;s APIs and may be changed, limited, or revoked by Meta at any time.
        </li>
        <li>
          You can disconnect the integration at any time; access tokens can be revoked from your
          Instagram or Meta account settings, which stops further processing.
        </li>
      </UL>

      <H2>5. AI-generated content</H2>
      <P>
        Replies and other content produced by the Service are generated by AI models and may be
        inaccurate, incomplete, or inappropriate for a given context. You are responsible for the
        content that is sent or published through your connected accounts and for reviewing automated
        behaviour where appropriate.
      </P>

      <H2>6. Availability and changes</H2>
      <P>
        The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We may
        modify, suspend, or discontinue any part of the Service at any time, and we do not guarantee
        uninterrupted or error-free operation.
      </P>

      <H2>7. Disclaimer of warranties</H2>
      <P>
        To the maximum extent permitted by law, the Service is provided without warranties of any kind,
        whether express or implied, including fitness for a particular purpose, non-infringement, and
        the accuracy or reliability of AI output.
      </P>

      <H2>8. Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, the operator shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, or for any loss of profits, data,
        goodwill, or account access, arising from or related to your use of the Service. Nothing in
        these Terms limits liability that cannot be limited under applicable law.
      </P>

      <H2>9. Suspension and termination</H2>
      <P>
        We may suspend or terminate access if these Terms are breached or the Service is misused. You
        may stop using the Service and disconnect your accounts at any time. On termination, data is
        handled as described in our <A href="/privacy">Privacy Policy</A>, and you may request deletion
        via the <A href="/data-deletion">Data Deletion</A> page.
      </P>

      <H2>10. Governing law</H2>
      <P>
        These Terms are governed by the laws of the Slovak Republic, without regard to conflict-of-law
        rules, and subject to any mandatory consumer-protection rights available to you.
      </P>

      <H2>11. Changes to these Terms</H2>
      <P>
        We may update these Terms from time to time. Material changes are reflected by updating the
        &ldquo;Last updated&rdquo; date at the top of this page. Continued use after changes take effect
        constitutes acceptance.
      </P>

      <H2>12. Contact</H2>
      <P>
        {LEGAL_OPERATOR} — <A href={`mailto:${LEGAL_CONTACT}`}>{LEGAL_CONTACT}</A>.
      </P>
    </LegalLayout>
  );
}
